#!/usr/bin/env bash
set -euo pipefail

UNIFIER_DIR=$(readlink -f $(dirname $0))
VERSION=$(grep -A1 "<artifactId>unifier</artifactId>" ${UNIFIER_DIR}/pom.xml | grep "<version>" | sed 's|.*<version>\(.*\)</version>.*|\1|')
java -jar ${UNIFIER_DIR}/target/unifier-$VERSION.jar $@
